### ISSUE TITLE
Allow to search history for site root by URL

### ISSUE THREAD

**Issue by dspechnikov** [deanishe/alfred-safari-assistant#14]
I frequently want to open the website root URL I visited earlier. I.e., `google.com`. From my experience, both `bh` and `hi` actions give higher precedence to page title, not URL. So even if I type `bh google.com` or `hi google.com`, I may not receive it as the first result.

I'd like to have something similar to Safari address bar behavior. It shows root site URL first and relevant history items next. It may be a separate action to preserve current behavior if needed.

**Comment by deanishe** [comment]
> both bh and hi actions give higher precedence to page title

`hi` only searches titles. `bh` also considers the URL, but yes, title is prioritised.

> I'd like to have something similar to Safari address bar behavior

That's not going to happen, I'm afraid. Safari is carrying out *at least* 3 separate searches when you enter something in the URL bar and merging/ranking the results. That's really beyond the scope of this workflow.

Bottom line, the workflow assumes you're going to use Alfred's knowledge to prioritise your results. If "google.com" is in your history, you only need to select it once or twice for Alfred to associate it with the query you entered. After that, it will *always* be the top result for that query.

Even if I did add the domain to the search, that often isn't going to work as expected because Alfred is ultimately in charge of ordering the results, and it does so based on your past behaviour.

**Comment by dspechnikov** [comment]
@deanishe fair enough, thanks for considering.
