### ISSUE TITLE
Add ability to save and retrieve Safari Sessions

### ISSUE THREAD

**Issue by nikivdev** [deanishe/alfred-safari-assistant#16]
Wanted to run this by you first as it might be out of scope for this workflow.

But there is a cool Safari extension that lets you save your current Safari tabs into sessions.

https://sessions-extension.github.io/Sessions/

And then retrieve them.

I wanted to build an Alfred alternative to it.

So users can press a hotkey and it saves all tabs into a session with a time stamp and number of items. And then have a script filter that searches over these sessions to restore.

**Comment by nikivdev** [comment]
Should be pretty simple to make as I already know the code needed to retrieve all the open safari tabs. Your Safari Go lib may do this too even and if not it can be extended to achieve this.

What do you think?

**Comment by deanishe** [comment]
Good idea.

> Your Safari Go lib may do this

It does. I mean, one of its jobs is to provide a list of all open tabs.

All the work is in implementing the front-end.

Out of interest, does the history search still work for you? I always get a "database is locked" error on High Sierra, but nobody else has reported the same problem…

**Comment by nikivdev** [comment]
> does the history search still work for you

Works flawlessly. Fast too. 🙂

**Comment by deanishe** [comment]
You're using a release, aren't you? I mean, you didn't build it yourself.

Because it looks like I've broken something or the SQLite library has changed something.

**Comment by nikivdev** [comment]
I am using v0.5 from releases yes.

**Comment by deanishe** [comment]
Thanks.

Back on topic, I wonder if it's better to name the sessions rather than just use date+time.

Alfred can't show the list of sessions and their contents at the same time, so names might be clearer.

Perhaps ask for a name, and if the user doesn't enter one, then use date+time for the name.

**Comment by nikivdev** [comment]
> Perhaps ask for a name, and if the user doesn't enter one, then use date+time for the name.

That's what I had in mind actually. Will try get a PR running because I miss Go now that I tried JavaScript.

**Comment by nikivdev** [comment]
Also I thought about letting users not only restoring sessions but going 'inside' each session and searching through the saved tabs too. Or even create a way to search across all tabs through all sessions in one interface. (acts like History but more focused on tabs you actually care about)

**Comment by deanishe** [comment]
> I miss Go now that I tried JavaScript

:grin: Yeah, JavaScript is not the best designed language, is it?

For my part, I think it's great that you learnt another language (that isn't PHP) first. It makes you sensitive to all the really dumb shit that JS does, and perhaps more importantly, all the dumb shit JS *developers* do.

I've had some [big arguments](https://github.com/derimagia/awesome-alfred-workflows/pull/46) with JS devs because they're so incredibly myopic.

**Comment by nikivdev** [comment]
> JavaScript is not the best designed language

It has its quirks yeah. TypeScript is pretty awesome though. I like the gradual typing approach and TS type system is quite expressive.

But from my short time in JS land, I do think that this ecosystem can do well with learning some [Go proverbs](https://go-proverbs.github.io). I do feel like so much care was put into making Go simple yet so productive that it makes working with it very pleasant.

Also I thought Go was hard. But working on complex web apps is so hard when everything is not neatly isolated and easy to reason about. Writing small tools and workflows is like a breath of fresh air.

**Comment by deanishe** [comment]
> learning some Go proverbs

TBH, a lot of that is incompatible with JS because it's single-threaded and can't do proper concurrency the way Go can.

> I do feel like so much care was put into making Go simple yet so productive

You're exactly right. It was. You can see the same thing with Python and Ruby.

JavaScript was literally thrown together in a few days to solve *very* trivial problems, and it *still* shows. The same largely applies to PHP.

> Also I thought Go was hard

Go isn't "hard" so much as "correct". Like Python, the language is constructed in a way that strongly encourages good coding practices. And Go is a far simpler language than Python, too.

I like Go because these days, it's arguably a better fit with the [Zen of Python](https://www.python.org/dev/peps/pep-0020/#the-zen-of-python) than Python itself is. And 20x faster, which is super cool.

**Comment by nikivdev** [comment]
> TBH, a lot of that is incompatible with JS

When I referred to the proverbs I actually meant to link to only one. 

> A little copying is better than a little dependency.

So much of JS is built on depending on trivial things that you can easily copy and paste to your code.

**Comment by sundarv85** [comment]
+1 Looking forward for the sessions support in Alfred. This looks pretty interesting.

**Comment by deanishe** [comment]
@sundarv85 Please don't add comments that just say "+1". Add a thumbs-up to the first post instead.

**Comment by andreiborisov** [comment]
Is it being worked on? Deprecation of Sessions extension driving me crazy, since now I forced to leave everything open and on top of that, every script/Alfred workflow opens new tab in existent window, even if it's in another Space...it's a mess.

Unfortunately, I'm not familiar with Go to help, but please count me in, if you need to test something.

**Comment by nikivdev** [comment]
> Is it being worked on?

I plan to add it at some point. Will update the issue when I make any progress.

**Comment by deanishe** [comment]
> every script/Alfred workflow opens new tab in existent window, even if it's in another Space...it's a mess

That's Safari's doing, and that's an issue that should be addressed by Apple. It's unrealistic to expect every other script/workflow/application to try to work around it.

**Comment by andreiborisov** [comment]
> That's Safari's doing, and that's an issue that should be addressed by Apple. It's unrealistic to expect every other script/workflow/application to try to work around it.

I completely agree with you, I'm just trying to convey another reason why sessions functionality would be incredibly helpful to have.

That said, I've opened different issue on this topic (https://github.com/deanishe/alfred-safari-assistant/issues/23). I would really appreciate some advice on how I can marry my workaround with Safari Assistant in particular, if such functionality isn't needed in Safari Assistant itself.

**Comment by deanishe** [comment]
> That said, I've opened different issue on this topic

You make some good points.

I'll have a think about how I can best adapt the workflow to make it more flexible. Seeing as the workflow is largely based around scripts, I'm currently thinking that allowing users to set a script as the default action for URLs would be the most suitable solution.
