### ISSUE TITLE
Bug: Workflow update does not do anything

### ISSUE THREAD

**Issue by Acidham** [deanishe/alfred-safari-assistant#33]
I triggered the Workflow update but "Fetching Updates" stays forever. 

# Versions
* Alfred version: 4
* macOS version:10.14.5
* Safari Assistant: 0.7.2

## Expected behaviour

Show that I am on latest version or update workflow notification

## Actual behaviour

Stalled in Fetching Update

## Steps to reproduce

1. Enter "safass" > Safari Assistance Config
2. Check for Updates

## Debugger output

15:39:17 update.go:154: Latest release: 0.7.2
15:39:17 magic.go:287: No update available

```

```

**Comment by Acidham** [comment]
Just saw few lines were missing in my previous post but seems to be important: 

```
15:33:42 update.go:328: Fetching https://api.github.com/repos/deanishe/alfred-safari-assistant/releases ...
15:33:42 update.go:334: [200] https://api.github.com/repos/deanishe/alfred-safari-assistant/releases
15:33:42 github.go:91: invalid release: no workflow files in release v0.4.5
15:33:42 github.go:58: 17 release(s) in repo deanishe/alfred-safari-assistant
15:33:42 update.go:154: Latest release: 0.7.2
15:33:42 magic.go:287: No update available
```

**Comment by deanishe** [comment]
You have the latest version already. This is the expected behaviour.

I can make the “Check for Update” message clearer (e.g. “Workflow is up to date”), but showing a notification would require rewriting the update mechanism.

Currently, it uses the library’s built-in update mechanism and that has no ability to show notifications.

**Comment by Acidham** [comment]
For user experience it would be better to tell that wf is up to date. I assume checking logs is not a solution.

Anyhow minor improvement.

**Comment by deanishe** [comment]
> For user experience it would be better to tell that wf is up to date

That’s not so clear cut because the information might be out of date.

In any case, the workflow will tell you when an update is available.

Perhaps I should just remove that item from the settings. It’d be a lot of work to make a very minor feature work provide accurate feedback.

That would hide the update mechanism from people who don’t already know how it works, and knowing how it works, they won’t be confused by the (lack of) feedback.

**Comment by Acidham** [comment]
Got it! In that case automatic update request in the background would be better like OneUpdater.

But I don't want to stretch this topic. Feel free to close....the WF is great!

**Comment by deanishe** [comment]
> Got it! In that case automatic update request in the background would be better like OneUpdater.

That’s already how it works. There is no need to check for updates manually.

I’m not going to change the workflow to automatically download and install updates, however, as I dislike that behaviour in OneUpdater.
